# $FreeBSD$

.if ${MACHINE_CPUARCH} == "aarch64"
SUBDIR= if_axa
.elif ${MACHINE_CPUARCH} == "amd64"
SUBDIR= if_axp
.endif

.include <bsd.subdir.mk>
# $FreeBSD$

SUBDIR= if_axa if_axp

.include <bsd.subdir.mk>
